apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx02
  name: nginx02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx02
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx02
        apps: nginx
    spec:
      volumes:
      - name: workdir
        emptyDir: {}
      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
          volumeMounts:
          - name: workdir
            mountPath: /usr/share/nginx/html
  # These containers are run during pod initialization
      initContainers:
      - name: install
        image: busybox
        command:
        - sh
        - -c
        args:
        - echo "nginx02" >  /work-dir/index.html
        volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
